"""
Documentation Agent.
Generates README.md for the generated project directly from the
build's actual state -- requirements, architecture, files written,
test results, scores. No LLM call: documentation must be generated
from actual project state, not hallucinated (PDF section 19).
"""


def generate_readme(report: dict) -> str:
    lines = []
    request = report.get("request", "").strip() or "Generated Project"
    lines.append(f"# {request}\n")
    lines.append("_Generated by AURA -- Autonomous Unified Software Engineering Agent._\n")

    spec = report.get("requirements_spec") or {}
    frs = spec.get("functional_requirements", [])
    if frs:
        lines.append("## Requirements\n")
        for fr in frs:
            lines.append(f"- **{fr.get('id')}**: {fr.get('description')}")
        lines.append("")

    architecture = report.get("architecture") or {}
    stack = architecture.get("stack", {})
    if stack:
        lines.append("## Tech Stack\n")
        for key, value in stack.items():
            lines.append(f"- **{key.capitalize()}**: {value}")
        if architecture.get("needs_database"):
            lines.append("- **Database**: yes (see schema.sql)")
        lines.append("")

    files = report.get("files_written", [])
    if files:
        lines.append("## Files\n")
        for f in sorted(files):
            lines.append(f"- `{f}`")
        lines.append("")

    lines.append("## Setup\n")
    if "requirements.txt" in files:
        lines.append("```bash")
        lines.append("pip install -r requirements.txt")
        lines.append("```\n")

    test_result = report.get("test_result", {})
    status = "PASSED" if test_result.get("passed") else "FAILED"
    passed_n = test_result.get("passed_count", 0)
    failed_n = test_result.get("failed_count", 0)
    lines.append("## Tests\n")
    lines.append(f"Status: **{status}** ({passed_n} passed, {failed_n} failed)\n")
    lines.append("```bash")
    lines.append("pytest")
    lines.append("```\n")

    scores = report.get("scores")
    if scores:
        lines.append("## AURA Score\n")
        lines.append(f"- Requirements: {scores['requirements']}%")
        lines.append(f"- Tests: {scores['tests']}%")
        lines.append(f"- Security: {scores['security']}%")
        lines.append(f"- Code Quality: {scores['code_quality']}%")
        lines.append(f"- **Overall: {scores['overall']}%**\n")

    gate = report.get("release_gate")
    if gate:
        lines.append("## Release Gate\n")
        lines.append(f"**{gate['status']}**\n")
        for reason in gate.get("reasons", []):
            lines.append(f"- {reason}")
        lines.append("")

    trace = report.get("traceability")
    if trace:
        lines.append("## Requirement Traceability\n")
        lines.append("| ID | File | Status |")
        lines.append("|---|---|---|")
        for t in trace:
            lines.append(f"| {t['requirement_id']} | {t['file'] or '-'} | {t['status']} |")
        lines.append("")

    security_result = report.get("security_result", {})
    dependency_result = report.get("dependency_result", {})
    findings = security_result.get("findings", [])
    dep_findings = dependency_result.get("findings", [])
    if findings or dep_findings:
        lines.append("## Known Issues\n")
        order = {"high": 0, "medium": 1, "low": 2}
        for f in sorted(findings, key=lambda x: order.get(x.get("severity"), 3)):
            lines.append(f"- `[{f.get('severity', '?').upper()}]` `{f['file']}:{f['line']}` -- {f['issue']}")
        for f in sorted(dep_findings, key=lambda x: order.get(x.get("severity"), 3)):
            lines.append(f"- `[{f.get('severity', '?').upper()}]` {f['package']} -- {f['id']} ({f.get('source')})")
        lines.append("")

    return "\n".join(lines)
